# Generated by Django 5.1.7 on 2025-04-06 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.CharField(max_length=70)),
                ('user_passwold', models.CharField(max_length=20)),
                ('user_wallet', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanks_title', models.CharField(max_length=70)),
                ('tanks_cost', models.CharField(max_length=70)),
                ('tanks_nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.nation')),
            ],
        ),
        migrations.CreateModel(
            name='favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorites_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.client')),
                ('favorites_tanks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.tanks')),
            ],
        ),
        migrations.CreateModel(
            name='corzine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date pokupki')),
                ('corzine_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.client')),
                ('corzine_tanks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.tanks')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
